/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { setupWorker, rest } from "msw";
import { faker } from "@faker-js/faker";

faker.seed(1);

const baseURL = "http://localhost:3000";
const MAX_ARRAY_LENGTH = 5;

let i = 0;
const next = () => {
  if (i === Number.MAX_SAFE_INTEGER - 1) {
    i = 0;
  }
  return i++;
};

export const handlers = [
  rest.get(`${baseURL}/menu`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getMenuControllerFindAll200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/menu`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getMenuControllerCreateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/menu/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getMenuControllerFindOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.patch(`${baseURL}/menu/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getMenuControllerUpdateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/auth/login`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAuthControllerLogin200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/auth/register`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAuthControllerRegister200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/address`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAddressControllerFindByUser200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/address`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAddressControllerCreateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.patch(`${baseURL}/address/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAddressControllerUpdateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.delete(`${baseURL}/address/:id`, (_, res, ctx) => {
    const resultArray = [[ctx.status(200), ctx.json(null)]];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/laundry-job`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getLaundryJobControllerFindAll200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/laundry-job`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getLaundryJobControllerCreateOne200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/laundry-job/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getLaundryJobControllerFindOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.patch(`${baseURL}/laundry-job/:id`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getLaundryJobControllerUpdateOne200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/laundry-job/user/:id`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getLaundryJobControllerFindByUser200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/job-items/:laundryJobId`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getJobItemsControllerFindByJobId200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.patch(`${baseURL}/job-items/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getJobItemsControllerUpdateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.delete(`${baseURL}/job-items/:id`, (_, res, ctx) => {
    const resultArray = [[ctx.status(200), ctx.json(null)]];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/job-items`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getJobItemsControllerCreateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/user/me/profile`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getUserControllerFindOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/user/me/laundry`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getUserControllerFindMyLaundryJob200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
];

export function getMenuControllerFindAll200Response() {
  return [
    ...new Array(
      faker.datatype.number({ min: 1, max: MAX_ARRAY_LENGTH })
    ).keys(),
  ].map((_) => ({
    id: 1,
    name: "Laundry Wash",
    price: 120,
    createdAt: "2022-06-30T08:46:57.941Z",
    updatedAt: "2022-10-01T04:37:06.695Z",
  }));
}

export function getMenuControllerCreateOne200Response() {
  return {
    id: 1,
    name: "Laundry Wash",
    price: 120,
    createdAt: "2022-06-30T08:46:57.941Z",
    updatedAt: "2022-10-01T04:37:06.695Z",
  };
}

export function getMenuControllerFindOne200Response() {
  return {
    id: 1,
    name: "Laundry Wash",
    price: 120,
    createdAt: "2022-06-30T08:46:57.941Z",
    updatedAt: "2022-10-01T04:37:06.695Z",
  };
}

export function getMenuControllerUpdateOne200Response() {
  return {
    id: 1,
    name: "Laundry Wash",
    price: 120,
    createdAt: "2022-06-30T08:46:57.941Z",
    updatedAt: "2022-10-01T04:37:06.695Z",
  };
}

export function getAuthControllerLogin200Response() {
  return {
    access_token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthcmwucmV2aWxsYUBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjc4NDQ3Mzg2fQ.2B3Q1Cxh1dV3TjIWNdMKbao3K0rG1e3PlLUpwdoGMKg",
  };
}

export function getAuthControllerRegister200Response() {
  return {
    access_token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthcmwucmV2aWxsYUBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjc4NDQ3Mzg2fQ.2B3Q1Cxh1dV3TjIWNdMKbao3K0rG1e3PlLUpwdoGMKg",
  };
}

export function getAddressControllerFindByUser200Response() {
  return [
    ...new Array(
      faker.datatype.number({ min: 1, max: MAX_ARRAY_LENGTH })
    ).keys(),
  ].map((_) => ({
    id: 1,
    address: "Manila, Philippines",
    createdAt: "2022-06-15T15:58:16.067Z",
    updatedAt: "2023-04-02T03:13:28.896Z",
  }));
}

export function getAddressControllerCreateOne200Response() {
  return {
    id: 1,
    address: "Manila, Philippines",
    createdAt: "2022-06-15T15:58:16.067Z",
    updatedAt: "2023-04-02T03:13:28.896Z",
  };
}

export function getAddressControllerUpdateOne200Response() {
  return {
    id: 1,
    address: "Manila, Philippines",
    createdAt: "2022-06-15T15:58:16.067Z",
    updatedAt: "2023-04-02T03:13:28.896Z",
  };
}

export function getLaundryJobControllerFindAll200Response() {
  return [
    ...new Array(
      faker.datatype.number({ min: 1, max: MAX_ARRAY_LENGTH })
    ).keys(),
  ].map((_) => ({
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-11-22T17:37:59.252Z",
    updatedAt: "2022-06-30T14:28:42.548Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-06-30T08:46:57.941Z",
          updatedAt: "2022-10-01T04:37:06.695Z",
        },
        createdAt: "2023-04-16T19:34:13.579Z",
        updatedAt: "2023-02-27T15:32:22.107Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2023-02-03T08:49:22.559Z",
          updatedAt: "2022-10-15T11:12:14.209Z",
        },
        createdAt: "2022-07-31T11:03:19.339Z",
        updatedAt: "2022-12-23T14:08:38.343Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-10-30T21:56:48.124Z",
          updatedAt: "2022-06-12T10:03:45.537Z",
        },
        createdAt: "2022-06-30T12:46:28.892Z",
        updatedAt: "2022-10-04T04:43:44.169Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2023-02-04T15:32:21.272Z",
          updatedAt: "2022-08-31T07:07:48.865Z",
        },
        createdAt: "2023-04-13T18:17:02.651Z",
        updatedAt: "2023-03-23T23:08:03.362Z",
      },
    ],
  }));
}

export function getLaundryJobControllerCreateOne200Response() {
  return {
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-11-22T17:37:59.252Z",
    updatedAt: "2022-06-30T14:28:42.548Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-06-30T08:46:57.941Z",
          updatedAt: "2022-10-01T04:37:06.695Z",
        },
        createdAt: "2023-04-16T19:34:13.579Z",
        updatedAt: "2023-02-27T15:32:22.107Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2023-02-03T08:49:22.559Z",
          updatedAt: "2022-10-15T11:12:14.209Z",
        },
        createdAt: "2022-07-31T11:03:19.339Z",
        updatedAt: "2022-12-23T14:08:38.343Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-10-30T21:56:48.124Z",
          updatedAt: "2022-06-12T10:03:45.537Z",
        },
        createdAt: "2022-06-30T12:46:28.892Z",
        updatedAt: "2022-10-04T04:43:44.169Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2023-02-04T15:32:21.272Z",
          updatedAt: "2022-08-31T07:07:48.865Z",
        },
        createdAt: "2023-04-13T18:17:02.651Z",
        updatedAt: "2023-03-23T23:08:03.362Z",
      },
    ],
  };
}

export function getLaundryJobControllerFindOne200Response() {
  return {
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-11-22T17:37:59.252Z",
    updatedAt: "2022-06-30T14:28:42.548Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-06-30T08:46:57.941Z",
          updatedAt: "2022-10-01T04:37:06.695Z",
        },
        createdAt: "2023-04-16T19:34:13.579Z",
        updatedAt: "2023-02-27T15:32:22.107Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2023-02-03T08:49:22.559Z",
          updatedAt: "2022-10-15T11:12:14.209Z",
        },
        createdAt: "2022-07-31T11:03:19.339Z",
        updatedAt: "2022-12-23T14:08:38.343Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-10-30T21:56:48.124Z",
          updatedAt: "2022-06-12T10:03:45.537Z",
        },
        createdAt: "2022-06-30T12:46:28.892Z",
        updatedAt: "2022-10-04T04:43:44.169Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2023-02-04T15:32:21.272Z",
          updatedAt: "2022-08-31T07:07:48.865Z",
        },
        createdAt: "2023-04-13T18:17:02.651Z",
        updatedAt: "2023-03-23T23:08:03.362Z",
      },
    ],
  };
}

export function getLaundryJobControllerUpdateOne200Response() {
  return {
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-11-22T17:37:59.252Z",
    updatedAt: "2022-06-30T14:28:42.548Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-06-30T08:46:57.941Z",
          updatedAt: "2022-10-01T04:37:06.695Z",
        },
        createdAt: "2023-04-16T19:34:13.579Z",
        updatedAt: "2023-02-27T15:32:22.107Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2023-02-03T08:49:22.559Z",
          updatedAt: "2022-10-15T11:12:14.209Z",
        },
        createdAt: "2022-07-31T11:03:19.339Z",
        updatedAt: "2022-12-23T14:08:38.343Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-10-30T21:56:48.124Z",
          updatedAt: "2022-06-12T10:03:45.537Z",
        },
        createdAt: "2022-06-30T12:46:28.892Z",
        updatedAt: "2022-10-04T04:43:44.169Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2023-02-04T15:32:21.272Z",
          updatedAt: "2022-08-31T07:07:48.865Z",
        },
        createdAt: "2023-04-13T18:17:02.651Z",
        updatedAt: "2023-03-23T23:08:03.362Z",
      },
    ],
  };
}

export function getLaundryJobControllerFindByUser200Response() {
  return [
    ...new Array(
      faker.datatype.number({ min: 1, max: MAX_ARRAY_LENGTH })
    ).keys(),
  ].map((_) => ({
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-11-22T17:37:59.252Z",
    updatedAt: "2022-06-30T14:28:42.548Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-06-30T08:46:57.941Z",
          updatedAt: "2022-10-01T04:37:06.695Z",
        },
        createdAt: "2023-04-16T19:34:13.579Z",
        updatedAt: "2023-02-27T15:32:22.107Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2023-02-03T08:49:22.559Z",
          updatedAt: "2022-10-15T11:12:14.209Z",
        },
        createdAt: "2022-07-31T11:03:19.339Z",
        updatedAt: "2022-12-23T14:08:38.343Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-10-30T21:56:48.124Z",
          updatedAt: "2022-06-12T10:03:45.537Z",
        },
        createdAt: "2022-06-30T12:46:28.892Z",
        updatedAt: "2022-10-04T04:43:44.169Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2023-02-04T15:32:21.272Z",
          updatedAt: "2022-08-31T07:07:48.865Z",
        },
        createdAt: "2023-04-13T18:17:02.651Z",
        updatedAt: "2023-03-23T23:08:03.362Z",
      },
    ],
  }));
}

export function getJobItemsControllerFindByJobId200Response() {
  return [
    ...new Array(
      faker.datatype.number({ min: 1, max: MAX_ARRAY_LENGTH })
    ).keys(),
  ].map((_) => ({
    id: 1,
    jobId: 1,
    itemId: 1,
    item: {
      id: 1,
      name: "Laundry Wash",
      price: 120,
      createdAt: "2022-06-30T08:46:57.941Z",
      updatedAt: "2022-10-01T04:37:06.695Z",
    },
    quantity: 1,
    createdAt: "2023-04-16T19:34:13.579Z",
    updatedAt: "2023-02-27T15:32:22.107Z",
  }));
}

export function getJobItemsControllerUpdateOne200Response() {
  return {
    id: 1,
    jobId: 1,
    itemId: 1,
    item: {
      id: 1,
      name: "Laundry Wash",
      price: 120,
      createdAt: "2022-06-30T08:46:57.941Z",
      updatedAt: "2022-10-01T04:37:06.695Z",
    },
    quantity: 1,
    createdAt: "2023-04-16T19:34:13.579Z",
    updatedAt: "2023-02-27T15:32:22.107Z",
  };
}

export function getJobItemsControllerCreateOne200Response() {
  return {
    id: 1,
    jobId: 1,
    itemId: 1,
    item: {
      id: 1,
      name: "Laundry Wash",
      price: 120,
      createdAt: "2022-06-30T08:46:57.941Z",
      updatedAt: "2022-10-01T04:37:06.695Z",
    },
    quantity: 1,
    createdAt: "2023-04-16T19:34:13.579Z",
    updatedAt: "2023-02-27T15:32:22.107Z",
  };
}

export function getUserControllerFindOne200Response() {
  return {
    id: 1,
    firstName: "Theresa Morar",
    lastName: "Harold Farrell",
    contact: "639471433814",
    email: "Carole20@gmail.com",
    isVerified: faker.datatype.boolean(),
    userType: "regular",
    createdAt: "2022-07-20T02:06:36.496Z",
    updatedAt: "2022-08-20T07:19:19.414Z",
  };
}

export function getUserControllerFindMyLaundryJob200Response() {
  return [
    ...new Array(
      faker.datatype.number({ min: 1, max: MAX_ARRAY_LENGTH })
    ).keys(),
  ].map((_) => ({
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-11-22T17:37:59.252Z",
    updatedAt: "2022-06-30T14:28:42.548Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-06-30T08:46:57.941Z",
          updatedAt: "2022-10-01T04:37:06.695Z",
        },
        createdAt: "2023-04-16T19:34:13.579Z",
        updatedAt: "2023-02-27T15:32:22.107Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2023-02-03T08:49:22.559Z",
          updatedAt: "2022-10-15T11:12:14.209Z",
        },
        createdAt: "2022-07-31T11:03:19.339Z",
        updatedAt: "2022-12-23T14:08:38.343Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-10-30T21:56:48.124Z",
          updatedAt: "2022-06-12T10:03:45.537Z",
        },
        createdAt: "2022-06-30T12:46:28.892Z",
        updatedAt: "2022-10-04T04:43:44.169Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2023-02-04T15:32:21.272Z",
          updatedAt: "2022-08-31T07:07:48.865Z",
        },
        createdAt: "2023-04-13T18:17:02.651Z",
        updatedAt: "2023-03-23T23:08:03.362Z",
      },
    ],
  }));
}

// This configures a Service Worker with the given request handlers.
export const startWorker = () => {
  const worker = setupWorker(...handlers);
  worker.start();
};
