/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { setupWorker, rest } from "msw";
import { faker } from "@faker-js/faker";

faker.seed(1);

const baseURL = "https://laundry-service-api.onrender.com";
const MAX_ARRAY_LENGTH = 5;

let i = 0;
const next = () => {
  if (i === Number.MAX_SAFE_INTEGER - 1) {
    i = 0;
  }
  return i++;
};

export const handlers = [
  rest.get(`${baseURL}/menu`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getMenuControllerFindAll200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/menu`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getMenuControllerCreateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/menu/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getMenuControllerFindOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.patch(`${baseURL}/menu/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getMenuControllerUpdateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/auth/login`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAuthControllerLogin200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/auth/register`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAuthControllerRegister200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/address`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAddressControllerFindByUser200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/address`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAddressControllerCreateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.patch(`${baseURL}/address/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getAddressControllerUpdateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.delete(`${baseURL}/address/:id`, (_, res, ctx) => {
    const resultArray = [[ctx.status(200), ctx.json(null)]];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/laundry-job`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getLaundryJobControllerFindAll200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/laundry-job`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getLaundryJobControllerCreateOne200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/laundry-job/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getLaundryJobControllerFindOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.patch(`${baseURL}/laundry-job/:id`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getLaundryJobControllerUpdateOne200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/laundry-job/user/:id`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getLaundryJobControllerFindByUser200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/job-items/:laundryJobId`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getJobItemsControllerFindByJobId200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.patch(`${baseURL}/job-items/:id`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getJobItemsControllerUpdateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.delete(`${baseURL}/job-items/:id`, (_, res, ctx) => {
    const resultArray = [[ctx.status(200), ctx.json(null)]];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/job-items`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getJobItemsControllerCreateOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/user/me/profile`, (_, res, ctx) => {
    const resultArray = [
      [ctx.status(200), ctx.json(getUserControllerFindOne200Response())],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/user/me/laundry`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(getUserControllerFindMyLaundryJob200Response()),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
];

export function getMenuControllerFindAll200Response() {
  return [...new Array(MAX_ARRAY_LENGTH).keys()].map((_) => ({
    id: 1,
    name: "Laundry Wash",
    price: 120,
    createdAt: "2022-09-30T21:44:55.451Z",
    updatedAt: "2023-02-16T22:27:41.838Z",
  }));
}

export function getMenuControllerCreateOne200Response() {
  return {
    id: 1,
    name: "Laundry Wash",
    price: 120,
    createdAt: "2022-09-30T21:44:55.451Z",
    updatedAt: "2023-02-16T22:27:41.838Z",
  };
}

export function getMenuControllerFindOne200Response() {
  return {
    id: 1,
    name: "Laundry Wash",
    price: 120,
    createdAt: "2022-09-30T21:44:55.451Z",
    updatedAt: "2023-02-16T22:27:41.838Z",
  };
}

export function getMenuControllerUpdateOne200Response() {
  return {
    id: 1,
    name: "Laundry Wash",
    price: 120,
    createdAt: "2022-09-30T21:44:55.451Z",
    updatedAt: "2023-02-16T22:27:41.838Z",
  };
}

export function getAuthControllerLogin200Response() {
  return {
    access_token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthcmwucmV2aWxsYUBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjc4NDQ3Mzg2fQ.2B3Q1Cxh1dV3TjIWNdMKbao3K0rG1e3PlLUpwdoGMKg",
  };
}

export function getAuthControllerRegister200Response() {
  return {
    access_token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthcmwucmV2aWxsYUBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjc4NDQ3Mzg2fQ.2B3Q1Cxh1dV3TjIWNdMKbao3K0rG1e3PlLUpwdoGMKg",
  };
}

export function getAddressControllerFindByUser200Response() {
  return [...new Array(MAX_ARRAY_LENGTH).keys()].map((_) => ({
    id: 1,
    address: "Manila, Philippines",
    createdAt: "2022-10-10T07:04:39.751Z",
    updatedAt: "2022-04-05T07:06:01.358Z",
  }));
}

export function getAddressControllerCreateOne200Response() {
  return {
    id: 1,
    address: "Manila, Philippines",
    createdAt: "2022-10-10T07:04:39.751Z",
    updatedAt: "2022-04-05T07:06:01.358Z",
  };
}

export function getAddressControllerUpdateOne200Response() {
  return {
    id: 1,
    address: "Manila, Philippines",
    createdAt: "2022-10-10T07:04:39.751Z",
    updatedAt: "2022-04-05T07:06:01.358Z",
  };
}

export function getLaundryJobControllerFindAll200Response() {
  return [...new Array(MAX_ARRAY_LENGTH).keys()].map((_) => ({
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-08-07T13:33:17.216Z",
    updatedAt: "2022-05-01T04:36:15.124Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-09-30T21:44:55.451Z",
          updatedAt: "2023-02-16T22:27:41.838Z",
        },
        createdAt: "2022-08-09T06:43:05.436Z",
        updatedAt: "2022-06-01T01:15:24.402Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2022-09-08T04:27:20.539Z",
          updatedAt: "2023-01-29T06:11:27.772Z",
        },
        createdAt: "2023-01-14T12:06:56.264Z",
        updatedAt: "2023-01-05T10:12:36.104Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-04-28T10:25:20.089Z",
          updatedAt: "2022-05-22T21:12:07.370Z",
        },
        createdAt: "2022-04-15T17:03:21.290Z",
        updatedAt: "2022-03-31T22:43:21.777Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2022-04-10T11:22:28.082Z",
          updatedAt: "2022-08-30T12:19:57.225Z",
        },
        createdAt: "2022-07-25T00:40:25.342Z",
        updatedAt: "2022-11-20T01:00:24.732Z",
      },
    ],
  }));
}

export function getLaundryJobControllerCreateOne200Response() {
  return {
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-08-07T13:33:17.216Z",
    updatedAt: "2022-05-01T04:36:15.124Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-09-30T21:44:55.451Z",
          updatedAt: "2023-02-16T22:27:41.838Z",
        },
        createdAt: "2022-08-09T06:43:05.436Z",
        updatedAt: "2022-06-01T01:15:24.402Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2022-09-08T04:27:20.539Z",
          updatedAt: "2023-01-29T06:11:27.772Z",
        },
        createdAt: "2023-01-14T12:06:56.264Z",
        updatedAt: "2023-01-05T10:12:36.104Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-04-28T10:25:20.089Z",
          updatedAt: "2022-05-22T21:12:07.370Z",
        },
        createdAt: "2022-04-15T17:03:21.290Z",
        updatedAt: "2022-03-31T22:43:21.777Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2022-04-10T11:22:28.082Z",
          updatedAt: "2022-08-30T12:19:57.225Z",
        },
        createdAt: "2022-07-25T00:40:25.342Z",
        updatedAt: "2022-11-20T01:00:24.732Z",
      },
    ],
  };
}

export function getLaundryJobControllerFindOne200Response() {
  return {
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-08-07T13:33:17.216Z",
    updatedAt: "2022-05-01T04:36:15.124Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-09-30T21:44:55.451Z",
          updatedAt: "2023-02-16T22:27:41.838Z",
        },
        createdAt: "2022-08-09T06:43:05.436Z",
        updatedAt: "2022-06-01T01:15:24.402Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2022-09-08T04:27:20.539Z",
          updatedAt: "2023-01-29T06:11:27.772Z",
        },
        createdAt: "2023-01-14T12:06:56.264Z",
        updatedAt: "2023-01-05T10:12:36.104Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-04-28T10:25:20.089Z",
          updatedAt: "2022-05-22T21:12:07.370Z",
        },
        createdAt: "2022-04-15T17:03:21.290Z",
        updatedAt: "2022-03-31T22:43:21.777Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2022-04-10T11:22:28.082Z",
          updatedAt: "2022-08-30T12:19:57.225Z",
        },
        createdAt: "2022-07-25T00:40:25.342Z",
        updatedAt: "2022-11-20T01:00:24.732Z",
      },
    ],
  };
}

export function getLaundryJobControllerUpdateOne200Response() {
  return {
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-08-07T13:33:17.216Z",
    updatedAt: "2022-05-01T04:36:15.124Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-09-30T21:44:55.451Z",
          updatedAt: "2023-02-16T22:27:41.838Z",
        },
        createdAt: "2022-08-09T06:43:05.436Z",
        updatedAt: "2022-06-01T01:15:24.402Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2022-09-08T04:27:20.539Z",
          updatedAt: "2023-01-29T06:11:27.772Z",
        },
        createdAt: "2023-01-14T12:06:56.264Z",
        updatedAt: "2023-01-05T10:12:36.104Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-04-28T10:25:20.089Z",
          updatedAt: "2022-05-22T21:12:07.370Z",
        },
        createdAt: "2022-04-15T17:03:21.290Z",
        updatedAt: "2022-03-31T22:43:21.777Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2022-04-10T11:22:28.082Z",
          updatedAt: "2022-08-30T12:19:57.225Z",
        },
        createdAt: "2022-07-25T00:40:25.342Z",
        updatedAt: "2022-11-20T01:00:24.732Z",
      },
    ],
  };
}

export function getLaundryJobControllerFindByUser200Response() {
  return [...new Array(MAX_ARRAY_LENGTH).keys()].map((_) => ({
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-08-07T13:33:17.216Z",
    updatedAt: "2022-05-01T04:36:15.124Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-09-30T21:44:55.451Z",
          updatedAt: "2023-02-16T22:27:41.838Z",
        },
        createdAt: "2022-08-09T06:43:05.436Z",
        updatedAt: "2022-06-01T01:15:24.402Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2022-09-08T04:27:20.539Z",
          updatedAt: "2023-01-29T06:11:27.772Z",
        },
        createdAt: "2023-01-14T12:06:56.264Z",
        updatedAt: "2023-01-05T10:12:36.104Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-04-28T10:25:20.089Z",
          updatedAt: "2022-05-22T21:12:07.370Z",
        },
        createdAt: "2022-04-15T17:03:21.290Z",
        updatedAt: "2022-03-31T22:43:21.777Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2022-04-10T11:22:28.082Z",
          updatedAt: "2022-08-30T12:19:57.225Z",
        },
        createdAt: "2022-07-25T00:40:25.342Z",
        updatedAt: "2022-11-20T01:00:24.732Z",
      },
    ],
  }));
}

export function getJobItemsControllerFindByJobId200Response() {
  return [...new Array(MAX_ARRAY_LENGTH).keys()].map((_) => ({
    id: 1,
    jobId: 1,
    itemId: 1,
    item: {
      id: 1,
      name: "Laundry Wash",
      price: 120,
      createdAt: "2022-09-30T21:44:55.451Z",
      updatedAt: "2023-02-16T22:27:41.838Z",
    },
    quantity: 1,
    createdAt: "2022-08-09T06:43:05.436Z",
    updatedAt: "2022-06-01T01:15:24.402Z",
  }));
}

export function getJobItemsControllerUpdateOne200Response() {
  return {
    id: 1,
    jobId: 1,
    itemId: 1,
    item: {
      id: 1,
      name: "Laundry Wash",
      price: 120,
      createdAt: "2022-09-30T21:44:55.451Z",
      updatedAt: "2023-02-16T22:27:41.838Z",
    },
    quantity: 1,
    createdAt: "2022-08-09T06:43:05.436Z",
    updatedAt: "2022-06-01T01:15:24.402Z",
  };
}

export function getJobItemsControllerCreateOne200Response() {
  return {
    id: 1,
    jobId: 1,
    itemId: 1,
    item: {
      id: 1,
      name: "Laundry Wash",
      price: 120,
      createdAt: "2022-09-30T21:44:55.451Z",
      updatedAt: "2023-02-16T22:27:41.838Z",
    },
    quantity: 1,
    createdAt: "2022-08-09T06:43:05.436Z",
    updatedAt: "2022-06-01T01:15:24.402Z",
  };
}

export function getUserControllerFindOne200Response() {
  return {
    id: 1,
    firstName: "Jeffery Pagac",
    lastName: "Frank Green",
    contact: "639778170022",
    email: "Lindsey52@yahoo.com",
    isVerified: true,
    userType: "regular",
    createdAt: "2022-12-18T16:25:00.130Z",
    updatedAt: "2022-12-16T01:47:01.939Z",
  };
}

export function getUserControllerFindMyLaundryJob200Response() {
  return [...new Array(MAX_ARRAY_LENGTH).keys()].map((_) => ({
    id: 1,
    userId: 1,
    status: "pending",
    createdAt: "2022-08-07T13:33:17.216Z",
    updatedAt: "2022-05-01T04:36:15.124Z",
    items: [
      {
        id: 1,
        jobId: 1,
        itemId: 1,
        quantity: 1,
        item: {
          id: 1,
          name: "Laundry Wash",
          price: 120,
          createdAt: "2022-09-30T21:44:55.451Z",
          updatedAt: "2023-02-16T22:27:41.838Z",
        },
        createdAt: "2022-08-09T06:43:05.436Z",
        updatedAt: "2022-06-01T01:15:24.402Z",
      },
      {
        id: 2,
        jobId: 1,
        itemId: 2,
        quantity: 2,
        item: {
          id: 2,
          name: "Hand Wash",
          price: 10,
          createdAt: "2022-09-08T04:27:20.539Z",
          updatedAt: "2023-01-29T06:11:27.772Z",
        },
        createdAt: "2023-01-14T12:06:56.264Z",
        updatedAt: "2023-01-05T10:12:36.104Z",
      },
      {
        id: 3,
        jobId: 1,
        itemId: 3,
        quantity: 3,
        item: {
          id: 3,
          name: "Dry Clean",
          price: 200,
          createdAt: "2022-04-28T10:25:20.089Z",
          updatedAt: "2022-05-22T21:12:07.370Z",
        },
        createdAt: "2022-04-15T17:03:21.290Z",
        updatedAt: "2022-03-31T22:43:21.777Z",
      },
      {
        id: 4,
        jobId: 1,
        itemId: 4,
        quantity: 4,
        item: {
          id: 4,
          name: "Dryer",
          price: 110,
          createdAt: "2022-04-10T11:22:28.082Z",
          updatedAt: "2022-08-30T12:19:57.225Z",
        },
        createdAt: "2022-07-25T00:40:25.342Z",
        updatedAt: "2022-11-20T01:00:24.732Z",
      },
    ],
  }));
}

// This configures a Service Worker with the given request handlers.
export const startWorker = () => {
  const worker = setupWorker(...handlers);
  worker.start();
};
