name: Lost Pixel Update

on: [workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook components
        run: yarn build-storybook

      - name: Run Lost Pixel container
        id: lp
        uses: lost-pixel/lost-pixel@v3.4.0
        env:
          LOST_PIXEL_MODE: update
          LOST_PIXEL_CONFIG_DIR: "packages/mobile"
          
      - name: Change File Permissions
        if: ${{ failure() && steps.lp.conclusion == 'failure' }}
        run: sudo chown -R $USER:$USER .

      - name: Create Pull request
        uses: peter-evans/create-pull-request@v5
        if: ${{ failure() && steps.lp.conclusion == 'failure' }}
        with:
          commit-message: Update Lost-Pixel baselines
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: "lost-pixel-baselines/${{ github.ref_name }}"
          delete-branch: true
          title: "Lost Pixel updating baselines - ${{ github.ref_name }}"
          body: Automated baseline update PR - lost pixel
          draft: false
